language: android
jdk: oraclejdk8
sudo: false

env:
  global:
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
    - ADB_INSTALL_TIMEOUT=10
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_API_LEVEL=25
    - ANDROID_TAG=google_apis
    - ANDROID_BUILD_TOOLS_VERSION=25.0.1

android:
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

  components:
    # Use the latest revision of Android SDK Tools
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - tools # to install Android SDK tools 25.1.x

    # The BuildTools version used by your project
    - build-tools-${ANDROID_BUILD_TOOLS_VERSION}

     # The SDK version used to compile your project
    - android-${ANDROID_API_LEVEL}

    # For Google APIs
    - addon-google_apis-google-$ANDROID_API_LEVEL

    # Additional components
    - extra-android-m2repository

    # Specify at least one system image
    # if you need to run emulator(s) during your tests
    - sys-img-${ANDROID_ABI}-android-$ANDROID_API_LEVEL

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

before_install:
  - echo y | android update sdk --all --no-ui --force --filter build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - echo y | android update sdk --all --no-ui --force --filter android-$ANDROID_API_LEVEL
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

before_script:
# INSTRUMENTED TESTS ARE DISABLED - until Google or Travis fix the mess with emulation, only local tests are enabled
#  - echo no | android create avd --force -n test -t "android-"$ANDROID_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
#  - echo no | android create avd --force -n test -t android-16 --abi $ANDROID_ABI
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &

script:
#  - ./gradlew build connectedCheck jacocoTestReport --stacktrace
  - ./gradlew build jacocoTestReport --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
    email: false

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2/